# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bump < Formula
  desc "Bump semver git tag in yours repository"
  homepage "https://bump.flaticols.dev"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flaticols/bump/releases/download/v0.0.5/bump_Darwin_x86_64.tar.gz"
      sha256 "1838d85e4df501e221337acdefc0fd12109f46a4daee1b7ab6a5b5e0206f11e7"

      def install
        bin.install "bump"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flaticols/bump/releases/download/v0.0.5/bump_Darwin_arm64.tar.gz"
      sha256 "297f988fecf2bfeb5ace5d6b934a5c9c074681dff6af326183eee67c0d83a5a7"

      def install
        bin.install "bump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flaticols/bump/releases/download/v0.0.5/bump_Linux_x86_64.tar.gz"
        sha256 "0c35895a51b34e5c2008829a138947fe7841920feadc3c182eb0cb8df3167b46"

        def install
          bin.install "bump"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flaticols/bump/releases/download/v0.0.5/bump_Linux_arm64.tar.gz"
        sha256 "16e4d42b8233f5d62e8d36eb88241f5ff83a93577696d80ae9fa80e0f8d484b8"

        def install
          bin.install "bump"
        end
      end
    end
  end
end
