# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bump < Formula
  desc "Bump semver git tag in yours repository"
  homepage "https://bump.flaticols.dev"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flaticols/bump/releases/download/v0.0.4/bump_Darwin_x86_64.tar.gz"
      sha256 "4403a0ffed4f7d634e438fbad145618d77859a0064ebcfb709f5c84a5f4185ba"

      def install
        bin.install "bump"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flaticols/bump/releases/download/v0.0.4/bump_Darwin_arm64.tar.gz"
      sha256 "975afadf659ac1c0334c6cbdd4ec1a5c617aa56c78db528772d3e9d0bec5614c"

      def install
        bin.install "bump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flaticols/bump/releases/download/v0.0.4/bump_Linux_x86_64.tar.gz"
        sha256 "87808e0abe75a4baedfafce0f4fcac50997f0f701deaffb4fd766e3ab9e33035"

        def install
          bin.install "bump"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/flaticols/bump/releases/download/v0.0.4/bump_Linux_arm64.tar.gz"
        sha256 "64587cf0db5aa022e4271c34ea293554a6ac2e3e72284ac332b1e68b15b5fefc"

        def install
          bin.install "bump"
        end
      end
    end
  end
end
