# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gorefact < Formula
  desc "Go call-graph explorer with dependency rule checks and a Neovim UI"
  homepage "https://github.com/flaticols/gorefactor"
  version "0.0.15"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/flaticols/gorefactor/releases/download/v0.0.15/gorefact_Darwin_x86_64.tar.gz"
    sha256 "5c2aa3a39d78036f7c84a9912fa394daf225866cfc908cb213f29c53d5c964e1"

    define_method(:install) do
      bin.install "gorefact"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/flaticols/gorefactor/releases/download/v0.0.15/gorefact_Darwin_arm64.tar.gz"
    sha256 "6f8e2ac3d5b7d37271d323ea613fc8c262ff015ba1bd10849462225598d94e24"

    define_method(:install) do
      bin.install "gorefact"
    end
  end
end
